name: CI/CD Deploy to Netlify

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  deployments: write

concurrency:
  group: netlify-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

     # - run: npm ci --prefer-offline --no-audit

     # - name: Run Prettier (check)
       # run: npx prettier . --check

      # - run: npm run lint --if-present

      - run: npm run build
        env:
          NODE_ENV: production

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: dist
          path: dist
          retention-days: 1

      - name: Deploy Preview (PRs)
        if: github.event_name == 'pull_request'
        uses: nwtgck/actions-netlify@v3
        with:
          publish-dir: ./dist
          production-deploy: false
          github-deployment: true
          alias: pr-${{ github.event.number }}
          deploy-message: "PR #${{ github.event.number }} – ${{ github.sha }}"
          enable-commit-comment: false
          enable-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - name: Deploy Production (main)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: nwtgck/actions-netlify@v3
        with:
          publish-dir: ./dist
          production-deploy: true
          github-deployment: true
          deploy-message: "Main – ${{ github.sha }}"
          enable-commit-comment: false
          enable-pull-request-comment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
